EOF = "EOF"
INVALID_TOKEN = "INVALID_TOKEN"
LINE_END = "LINE_END"
WHITESPACE = "WHITESPACE"
GROUP_COMMENT = "GROUP_COMMENT"
COMMENT_MULTI = "COMMENT_MULTI"
COMMENT_NESTED = "COMMENT_NESTED"
COMMENT_LINE = "COMMENT_LINE"
DOCCOMMENT_MULTI = "DOCCOMMENT_MULTI"
DOCCOMMENT_NESTED = "DOCCOMMENT_NESTED"
DOCCOMMENT_LINE = "DOCCOMMENT_LINE"
SCRIPT_LINE_INTRO = "SCRIPT_LINE_INTRO"
SPECIAL_TOKEN_LINE = "SPECIAL_TOKEN_LINE"
IDENTIFIER = "IDENTIFIER"
STRING_WYSIWYG = "STRING_WYSIWYG"
STRING_DQ = "STRING_DQ"
STRING_HEX = "STRING_HEX"
STRING_DELIM = "STRING_DELIM"
STRING_TOKENS = "STRING_TOKENS"
CHARACTER = "CHARACTER"
INTEGER_DECIMAL = "INTEGER_DECIMAL"
INTEGER_BINARY = "INTEGER_BINARY"
INTEGER_OCTAL = "INTEGER_OCTAL"
INTEGER_HEX = "INTEGER_HEX"
FLOAT_DECIMAL = "FLOAT_DECIMAL"
FLOAT_HEX = "FLOAT_HEX"
OPEN_PARENS = "OPEN_PARENS"
CLOSE_PARENS = "CLOSE_PARENS"
OPEN_BRACE = "OPEN_BRACE"
CLOSE_BRACE = "CLOSE_BRACE"
OPEN_BRACKET = "OPEN_BRACKET"
CLOSE_BRACKET = "CLOSE_BRACKET"
SEMICOLON = "SEMICOLON"
COLON = "COLON"
QUESTION = "QUESTION"
COMMA = "COMMA"
DOLLAR = "DOLLAR"
AT = "AT"
DOT = "DOT"
DOUBLE_DOT = "DOUBLE_DOT"
TRIPLE_DOT = "TRIPLE_DOT"
DECREMENT = "DECREMENT"
INCREMENT = "INCREMENT"
MINUS = "MINUS"
MINUS_ASSIGN = "MINUS_ASSIGN"
PLUS = "PLUS"
PLUS_ASSIGN = "PLUS_ASSIGN"
DIV = "DIV"
DIV_ASSIGN = "DIV_ASSIGN"
STAR = "STAR"
MULT_ASSIGN = "MULT_ASSIGN"
MOD = "MOD"
MOD_ASSIGN = "MOD_ASSIGN"
POW = "POW"
POW_ASSIGN = "POW_ASSIGN"
AND = "AND"
AND_ASSIGN = "AND_ASSIGN"
OR = "OR"
OR_ASSIGN = "OR_ASSIGN"
XOR = "XOR"
XOR_ASSIGN = "XOR_ASSIGN"
CONCAT = "CONCAT"
CONCAT_ASSIGN = "CONCAT_ASSIGN"
LOGICAL_AND = "LOGICAL_AND"
LOGICAL_OR = "LOGICAL_OR"
LAMBDA = "LAMBDA"
ASSIGN = "ASSIGN"
EQUALS = "EQUALS"
NOT = "NOT"
NOT_EQUAL = "NOT_EQUAL"
LESS_THAN = "LESS_THAN"
LESS_EQUAL = "LESS_EQUAL"
GREATER_THAN = "GREATER_THAN"
GREATER_EQUAL = "GREATER_EQUAL"
LESS_GREATER = "LESS_GREATER"
LESS_GREATER_EQUAL = "LESS_GREATER_EQUAL"
UNORDERED_E = "UNORDERED_E"
UNORDERED = "UNORDERED"
UNORDERED_GE = "UNORDERED_GE"
UNORDERED_G = "UNORDERED_G"
UNORDERED_LE = "UNORDERED_LE"
UNORDERED_L = "UNORDERED_L"
LEFT_SHIFT = "LEFT_SHIFT"
LEFT_SHIFT_ASSIGN = "LEFT_SHIFT_ASSIGN"
RIGHT_SHIFT = "RIGHT_SHIFT"
RIGHT_SHIFT_ASSIGN = "RIGHT_SHIFT_ASSIGN"
TRIPLE_RSHIFT = "TRIPLE_RSHIFT"
TRIPLE_RSHIFT_ASSIGN = "TRIPLE_RSHIFT_ASSIGN"
KW_BOOL = "KW_BOOL"
KW_VOID = "KW_VOID"
KW_BYTE = "KW_BYTE"
KW_UBYTE = "KW_UBYTE"
KW_SHORT = "KW_SHORT"
KW_USHORT = "KW_USHORT"
KW_INT = "KW_INT"
KW_UINT = "KW_UINT"
KW_LONG = "KW_LONG"
KW_ULONG = "KW_ULONG"
KW_CENT = "KW_CENT"
KW_UCENT = "KW_UCENT"
KW_CHAR = "KW_CHAR"
KW_WCHAR = "KW_WCHAR"
KW_DCHAR = "KW_DCHAR"
KW_FLOAT = "KW_FLOAT"
KW_DOUBLE = "KW_DOUBLE"
KW_REAL = "KW_REAL"
KW_IFLOAT = "KW_IFLOAT"
KW_IDOUBLE = "KW_IDOUBLE"
KW_IREAL = "KW_IREAL"
KW_CFLOAT = "KW_CFLOAT"
KW_CDOUBLE = "KW_CDOUBLE"
KW_CREAL = "KW_CREAL"
KW_PRIVATE = "KW_PRIVATE"
KW_PACKAGE = "KW_PACKAGE"
KW_PROTECTED = "KW_PROTECTED"
KW_PUBLIC = "KW_PUBLIC"
KW_EXPORT = "KW_EXPORT"
KW_ABSTRACT = "KW_ABSTRACT"
KW_DEPRECATED = "KW_DEPRECATED"
KW_FINAL = "KW_FINAL"
KW_NOTHROW = "KW_NOTHROW"
KW_OVERRIDE = "KW_OVERRIDE"
KW_PURE = "KW_PURE"
KW_SCOPE = "KW_SCOPE"
KW_STATIC = "KW_STATIC"
KW_SYNCHRONIZED = "KW_SYNCHRONIZED"
KW_REF = "KW_REF"
KW_CONST = "KW_CONST"
KW_IMMUTABLE = "KW_IMMUTABLE"
KW_INOUT = "KW_INOUT"
KW_SHARED = "KW_SHARED"
KW_AUTO = "KW_AUTO"
KW_ALIAS = "KW_ALIAS"
KW_ALIGN = "KW_ALIGN"
KW_ASM = "KW_ASM"
KW_ASSERT = "KW_ASSERT"
KW_BODY = "KW_BODY"
KW_BREAK = "KW_BREAK"
KW_CASE = "KW_CASE"
KW_CAST = "KW_CAST"
KW_CATCH = "KW_CATCH"
KW_CLASS = "KW_CLASS"
KW_CONTINUE = "KW_CONTINUE"
KW_DEBUG = "KW_DEBUG"
KW_DEFAULT = "KW_DEFAULT"
KW_DELEGATE = "KW_DELEGATE"
KW_DELETE = "KW_DELETE"
KW_DO = "KW_DO"
KW_ELSE = "KW_ELSE"
KW_ENUM = "KW_ENUM"
KW_EXTERN = "KW_EXTERN"
KW_FALSE = "KW_FALSE"
KW_FINALLY = "KW_FINALLY"
KW_FOR = "KW_FOR"
KW_FOREACH = "KW_FOREACH"
KW_FOREACH_REVERSE = "KW_FOREACH_REVERSE"
KW_FUNCTION = "KW_FUNCTION"
KW_GOTO = "KW_GOTO"
KW_IF = "KW_IF"
KW_IMPORT = "KW_IMPORT"
KW_IN = "KW_IN"
KW_INTERFACE = "KW_INTERFACE"
KW_INVARIANT = "KW_INVARIANT"
KW_IS = "KW_IS"
KW_LAZY = "KW_LAZY"
KW_MACRO = "KW_MACRO"
KW_MIXIN = "KW_MIXIN"
KW_MODULE = "KW_MODULE"
KW_NEW = "KW_NEW"
KW_NULL = "KW_NULL"
KW_OUT = "KW_OUT"
KW_PRAGMA = "KW_PRAGMA"
KW_RETURN = "KW_RETURN"
KW_STRUCT = "KW_STRUCT"
KW_SUPER = "KW_SUPER"
KW_SWITCH = "KW_SWITCH"
KW_TEMPLATE = "KW_TEMPLATE"
KW_THIS = "KW_THIS"
KW_THROW = "KW_THROW"
KW_TRUE = "KW_TRUE"
KW_TRY = "KW_TRY"
KW_TYPEDEF = "KW_TYPEDEF"
KW_TYPEID = "KW_TYPEID"
KW_TYPEOF = "KW_TYPEOF"
KW_UNION = "KW_UNION"
KW_UNITTEST = "KW_UNITTEST"
KW_VERSION = "KW_VERSION"
KW_VOLATILE = "KW_VOLATILE"
KW_WHILE = "KW_WHILE"
KW_WITH = "KW_WITH"
KW___TRAITS = "KW___TRAITS"
KW___GSHARED = "KW___GSHARED"
KW___THREAD = "KW___THREAD"
KW___VECTOR = "KW___VECTOR"
KW___FILE__ = "KW___FILE__"
KW___LINE__ = "KW___LINE__"
KW___MODULE__ = "KW___MODULE__"
KW___FUNCTION__ = "KW___FUNCTION__"
KW___PRETTY_FUNCTION__ = "KW___PRETTY_FUNCTION__"
KW___DATE__ = "KW___DATE__"
KW___TIME__ = "KW___TIME__"
KW___TIMESTAMP__ = "KW___TIMESTAMP__"
KW___VENDOR__ = "KW___VENDOR__"
KW___VERSION__  = "__VERSION__"